[build]
  functions = "functions"
  publish = "dist"

[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true


[functions]
  send_email = { name = "send-email", schedule = "0 0 * * *" }
